#!groovy

pipeline {
  agent any
  environment {
    DOCKERHUB_CREDENTIALS = credentials('docker-hub-credentials')
    WORKSPACE_DIR = "node-function-app" // Define your custom directory
    DOCKER_HUB_USERNAME = "prasadreddy2349"
    IMAGE_NAME = "nodejs-azure-function-app-containerization-jenkins"
    IMAGE_TAG = "latest"
  }
  stages {
    stage('Workspace Cleanup') {
      steps {
        // Clean before build
        cleanWs()
        echo 'cleaning workspace...'
      }
    }
    stage('Checkout Git Branch') {
      steps {
        git branch: 'master', credentialsId: 'github-credentials', url: 'https://github.com/vprasadreddy/nodejs_azure_function_app_containerization.git'
      }
    }
    stage('scan image using trivy') {
      steps {
        dir(env.WORKSPACE_DIR) {
          //sh 'trivy image --severity HIGH,CRITICAL --scanners vuln ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}'
          sh 'trivy image --scanners vuln --format template --template "@/usr/local/share/trivy/templates/html.tpl" -o report.html ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}'
        }
      }
    }
    stage('publish trivy report') {
      steps {
        dir(env.WORKSPACE_DIR) {
          publishHTML(target: [allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportDir: '.',
            reportFiles: 'report.html',
            reportName: 'Trivy Scan Report',
            reportTitles: 'Trivy Scan Report'
          ])
        }
      }
    }
    stage('build docker image') {
      steps {
        dir(env.WORKSPACE_DIR) {
          sh 'docker build -t ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG} .'
        }
      }
    }
    stage('Push docker image') {
      steps {
        dir(env.WORKSPACE_DIR) {
          sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
          echo 'Login successful'
          sh 'docker push ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}'
        }
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}